[project]
name = "email-ai-assistant"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pywin32",
    "google-genai",
    "python-dotenv",
    "openpyxl",
    "reportlab"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["src*"]
